### ISSUE TITLE
Not working on Android

### ISSUE THREAD

**Issue by vaibhavn1** [VirtuoWorks/CanvasCameraPlugin#2] opened 2017-06-05 14:13 UTC
Hi 

Thanks for the great plugin. It worked fine on iOS , but is not working on Android Device. Tested on Nexus 6p Nougat. Following was shown in logcat when tested with demo app.

<img width="1283" alt="screen shot 2017-06-05 at 7 43 07 pm" src="https://cloud.githubusercontent.com/assets/4082467/26787331/3d4e9a84-4a27-11e7-982c-0bea5b33dd0b.png">

**Comment by Sami-Radi** [comment] 2017-06-05 14:24
Hello,

I've been testing the plugin on a Samsung 6s with Android 6.0 and had no such problem.

Could you turn on the logs (CanvasCamera.java -> line 42 -> private final static boolean LOGGING = true;) before building the app. It'll be more verbose. 

You have to change the  CanvasCamera.java file in the platform/android directory directly or :

1. Remove android platform;
2. Change CanvasCamera.java in plugin directory;
3. Add android platform again;
4. Build a release.

Thanks for reporting an issue.

**Comment by vaibhavn1** [comment] 2017-06-05 14:31
Ok i just tried that 

here is the log

06-05 20:00:27.375 10572-10572/io.cordova.hellocordova D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 62 : play
06-05 20:00:27.375 10572-10572/io.cordova.hellocordova I/chromium: [INFO:CONSOLE(62)] "play", source: file:///android_asset/www/js/index.js (62)
06-05 20:00:27.379 10572-10767/io.cordova.hellocordova I/CanvasCamera: Starting async startCapture thread...
06-05 20:00:27.384 3690-6227/? E/mm-camera-intf: mm_channel_fsm_fn_stopped: invalid state (1) for evt (6)
06-05 20:00:27.452 3690-6227/? I/Camera3-Device: disconnect: E
06-05 20:00:27.455 3690-6227/? I/QCamera3HWI: virtual qcamera::QCamera3HardwareInterface::~QCamera3HardwareInterface(): stopping channel 78592
06-05 20:00:27.458 3690-6227/? E/QCamera3HWI: virtual qcamera::QCamera3HardwareInterface::~QCamera3HardwareInterface(): deleting channel 78592
06-05 20:00:27.460 3702-11332/? E/mm-camera: mct: mct_pipeline_process_set:2306: Couldn't find stream id: 0
06-05 20:00:27.461 3702-3702/? E/mm-camera: port_iface_ext_unlink_func: E, identity = 0x3000f, port = 0xf3f2acc0, direction = 2
06-05 20:00:27.461 3702-3702/? E/mm-camera: port_iface_check_caps_unreserve_func:  E, identity = 0x3000f, port = 0xf3f2acc0, direction = 2
06-05 20:00:27.461 3702-3702/? E/mm-camera: iface_unreserve_sink_port: stream_id f mode 0 
06-05 20:00:27.461 3702-3702/? E/mm-camera: port_iface_ext_unlink_func: E, identity = 0x3000f, port = 0xf3f2afc0, direction = 1
06-05 20:00:27.461 3702-3702/? E/mm-camera: iface_ext_unlink_src_port: mct stream already removed from hw stream
06-05 20:00:27.461 3702-3702/? E/mm-camera: port_iface_check_caps_unreserve_func:  E, identity = 0x3000f, port = 0xf3f2afc0, direction = 1
06-05 20:00:27.461 3702-3702/? E/mm-camera: isp_port_check_caps_unreserve:844 ide 3000f port 0xf3eedc60
06-05 20:00:27.461 3702-3702/? E/mm-camera: c2d_port_check_caps_unreserve:183, identity=0x3000f
06-05 20:00:27.461 3702-3702/? E/mm-camera: c2d_port_check_caps_unreserve:193, identity=0x3000f, unreserved
06-05 20:00:27.461 3702-3702/? E/mm-camera: c2d_port_check_caps_unreserve:183, identity=0x3000f
06-05 20:00:27.461 3702-3702/? E/mm-camera: c2d_port_check_caps_unreserve:193, identity=0x3000f, unreserved
06-05 20:00:27.461 3702-3702/? E/mm-camera: cpp_port_check_caps_unreserve:164, identity=0x3000f
06-05 20:00:27.461 3702-3702/? E/mm-camera: cpp_port_check_caps_unreserve:174, identity=0x3000f, unreserved
06-05 20:00:27.461 3702-3702/? E/mm-camera: cpp_port_check_caps_unreserve:164, identity=0x3000f
06-05 20:00:27.461 3702-3702/? E/mm-camera: cpp_port_check_caps_unreserve:174, identity=0x3000f, unreserved
06-05 20:00:27.462 3702-3702/? E/mm-camera: q3a_thread_af_stop:679  q3a_thread_af_stop:679 MSG_STOP_THREAD
06-05 20:00:27.463 3702-3702/? D/mm-camera: stats_port_delete_reserved_stream:2426: going to NULL peer
06-05 20:00:27.464 3702-11365/? E/mm-camera-isp2: isp_module_stop_session:437 session id 3
06-05 20:00:27.466 3702-11367/? E/mm-camera: cpp_module_stop_session:552, info: stopping session 3 ...
06-05 20:00:27.466 3702-11324/? E/mm-camera: cpp_thread_process_pipe_message:584, CPP_THREAD_MSG_ABORT: cpp_thread exiting..
06-05 20:00:27.466 3702-11368/? E/mm-camera: module_faceproc_stop_session:1804] session cnt 1
06-05 20:00:27.468 3702-11367/? E/mm-camera: cpp_module_stop_session:601, info: session 3 stopped.
06-05 20:00:27.468 3702-11367/? E/mm-camera: c2d_module_stop_session:354, info: stopping session 3 ...
06-05 20:00:27.468 3702-11325/? E/mm-camera: c2d_thread_process_pipe_message:836, C2D_THREAD_MSG_ABORT: c2d_thread exiting..
06-05 20:00:27.469 3702-11367/? E/mm-camera: c2d_module_stop_session:399, info: session 3 stopped.
06-05 20:00:27.471 3702-11367/? E/cac2:  [cac2latency] cac2_destroy_buffers: 1 ms 
06-05 20:00:27.479 3690-6227/? I/CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=1
06-05 20:00:27.480 3690-6227/? I/Camera3-Device: disconnect: X
06-05 20:00:27.480 3690-6227/? I/Camera3-Device: disconnect: E
06-05 20:00:27.484 3690-6227/? I/CameraService: disconnect: Disconnected client for camera 0 for PID 10572
06-05 20:00:27.484 10572-10572/io.cordova.hellocordova I/CanvasCamera: Camera [0] stopped.
06-05 20:00:27.485 3690-6227/? I/Camera2Client: Camera 0: Closed
06-05 20:00:27.485 3690-6227/? I/Camera2ClientBase: Closed Camera 0. Client was: io.cordova.hellocordova (PID 10572, UID 10210)
06-05 20:00:27.486 3697-31551/? D/NuPlayerDriver: reset(0xeee2aea0) at state 4
06-05 20:00:27.486 3697-31551/? D/NuPlayerDriver: notifyListener_l(0xeee2aea0), (8, 0, 0), loop setting(0, 0)
06-05 20:00:27.486 10572-10572/io.cordova.hellocordova I/CanvasCamera: Trying to open camera : 0
06-05 20:00:27.486 3697-11306/? D/NuPlayerDriver: notifyResetComplete(0xeee2aea0)
06-05 20:00:27.487 3690-8493/? I/CameraService: CameraService::connect call (PID -1 "io.cordova.hellocordova", camera ID 0) for HAL version default and Camera API version 1
06-05 20:00:27.488 3697-31551/? D/NuPlayerDriver: reset(0xeee2b500) at state 4
06-05 20:00:27.488 3697-31551/? D/NuPlayerDriver: notifyListener_l(0xeee2b500), (8, 0, 0), loop setting(0, 0)
06-05 20:00:27.488 3697-11308/? D/NuPlayerDriver: notifyResetComplete(0xeee2b500)
06-05 20:00:27.490 3697-6753/? D/NuPlayerDriver: reset(0xeee2b8c0) at state 4
06-05 20:00:27.490 3697-6753/? D/NuPlayerDriver: notifyListener_l(0xeee2b8c0), (8, 0, 0), loop setting(0, 0)
06-05 20:00:27.490 3697-11310/? D/NuPlayerDriver: notifyResetComplete(0xeee2b8c0)
06-05 20:00:27.503 3697-11369/? D/NuPlayerDriver: notifyListener_l(0xeee2b8c0), (1, 0, 0), loop setting(0, 0)
06-05 20:00:27.513 3697-11371/? D/NuPlayerDriver: notifyListener_l(0xeee2b080), (1, 0, 0), loop setting(0, 0)
06-05 20:00:27.520 3697-11373/? D/NuPlayerDriver: notifyListener_l(0xeee2b0e0), (1, 0, 0), loop setting(0, 0)
06-05 20:00:27.521 3690-8493/? I/Camera2ClientBase: Camera 0: Opened. Client: io.cordova.hellocordova (PID 10572, UID 10210)
06-05 20:00:27.522 3690-8493/? I/CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0
06-05 20:00:27.525 3690-8493/? I/CameraService: onTorchStatusChangedLocked: Torch status changed for cameraId=0, newStatus=0

**Comment by vaibhavn1** [comment] 2017-06-05 15:59
Let me know if you need some other info :)

**Comment by Sami-Radi** [comment] 2017-06-08 16:50
I don't have the same phone as yours so i'm blind on this issue. I couldn't reproduce the bug.
However, I've done a few changes to the plugin. Tell me if there's any improvements regarding your issue with the latest version of the plugin.

Thanks.

**Comment by Sami-Radi** [comment] 2017-06-20 10:08
Any news ?

**Comment by vaibhavn1** [comment] 2017-06-20 10:11
Hello 

I have been travelling since last few days. Will try today and post the results
Sorry for the delay :(

**Comment by Sami-Radi** [comment] 2017-06-28 08:25
Hello,

We've been testing the latest version of the plugin on a One Plus 3T with Android 7.1.1 and no issue to report. 

I'm closing the issue.

**Closed as completed by Sami-Radi** 2017-06-28 08:25 UTC

**Comment by vaibhavn1** [comment] 2017-06-28 10:41
Hi Sami

Just tested the new version on my phone. Its working correctly now.

Thanks for your awesome work.
